services:
  pebble:
    build: .
    container_name: pebble-dev
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload --log-level debug
    ports:
      - 8080:80
    volumes:
      - .:/app
      - .:/api
  run-tests:
    build: .
    container_name: pebble-tests
    command: pytest /pebble/tests
    volumes:
      - .:/tests